import { Field, FieldType, FieldState } from "./field.js";

export const levels = {
    easy: [
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ]
    ],
    hard: [
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY)],
            [new Field(FieldType.MOUNTAIN, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY)],
            [new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 3, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ],
        [
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.BRIDGE, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 1, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.OASIS, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.MOUNTAIN, 2, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.BRIDGE, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)],
            [new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY), new Field(FieldType.EMPTY, 0, FieldState.EMPTY)]
        ]
    ]
};